name: 🐛 Bug Report
description: Report a problem to help us improve.
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: industry
    attributes:
      label: Industry Strategy
      description: Which industry strategy were you using?
      options:
        - General Retail
        - Apotek (Pharmacy)
        - Hotel
        - Fashion
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How did you encounter this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
